name: AsyncAPI documents processing

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      #"standard step" where repo needs to be checked-out first
      - name: Checkout repo
        uses: actions/checkout@v2

      #In case you do not want to use defaults, you for example want to use different template
      - name: Generating HTML from my AsyncAPI document
        uses: asyncapi/github-action-for-cli@v3.1.1 # You can use any version you want
        with:
          template: '@asyncapi/html-template@3.1.0'  #In case of template from npm, because of @ it must be in quotes
          filepath: dbus-websocket-asyncapi.json
          output: generated-html
          parameters: '--use-new-generator --debug'
          cli_version: '2.10.0'

      #Using another action that takes generated HTML and pushes it to GH Pages
      - name: Deploy GH page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: generated-html